const width = 10;
const height = 5;
const area = width * height;
console.log('value of area: ' + area);
console.log('type of area: ' + typeof area);
const bill = 10;
const payment = 20;
const change = payment - bill;
console.log('value of change: ' + change);
console.log('type of change: ' + typeof change);
const quizzes = 10;
const midterm = 10;
const final = 10;
const grade = (quizzes + midterm + final) / 3;
console.log('value of grade: ' + grade);
console.log('Type of grade: ' + typeof grade);
const firstName = 'Mohamed';
const lastName = 'Elmessiry';
const fullName = firstName + lastName;
console.log('value of fullName: ' + fullName);
console.log('type of fullName: ' + typeof fullName);
const pH = 10;
const isAcidic = pH > 7;
console.log('value of isAcidic: ' + isAcidic);
console.log('Type of isAcidic ' + typeof isAcidic);
const headCount = 15;
const isSparta = headCount === 300;
console.log('value of isSparta ' + isSparta);
console.log('Type of isSparta ' + typeof isSparta);
const motto = fullName + 'is the goat';
console.log('value of motto ' + motto);
console.log('Type of motto ' + typeof motto);
