var anObject = new Object();
console.log('value of anObject:', anObject);
console.log('typeof anObject:', typeof anObject);
var array = new Array();
console.log('value of array:', array);
console.log('type of array:', typeof array);
var func = new Function();
console.log('value of func:', func);
console.log('type of function:', typeof func);
var str = new String();
console.log('value of string:', str);
console.log('type of str:', typeof str);
var num = new Number();
console.log('value of num:', num);
console.log('type of num:', num);
var bol = new Boolean();
console.log('value of bol', bol);
console.log('type of bol', typeof bol);
